<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="
            http://maven.apache.org/POM/4.0.0
            https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <!-- Spring Boot -->
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.1</version>
        <relativePath/>
    </parent>

    <!-- Información de nuestro proyecto -->
    <groupId>com.recuperacion</groupId>
    <artifactId>rec-api</artifactId>
    <version>0.0.1-SNAPSHOT</version>

    <name>rec-api</name>

    <description>
        API Java Spring Boot para actividad DevSecOps
    </description>

    <!-- Versión de Java -->
    <properties>
        <java.version>21</java.version>

        <!--
            Spring Boot 4.1.1 usa Tomcat 11.0.24 por defecto.
            Actualizamos Tomcat porque Dependency-Check detectó CVEs
            corregidos en versiones posteriores.
        -->
        <tomcat.version>11.0.26</tomcat.version>
    </properties>

    <!-- Dependencias -->
    <dependencies>

        <!-- Permite crear una API REST con Spring Boot -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <!-- Dependencias para pruebas -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.apache.logging.log4j</groupId>
            <artifactId>log4j-core</artifactId>
            <version>2.14.1</version>
        </dependency>

    </dependencies>

    <!-- Configuración de compilación -->
    <build>

        <plugins>

            <!-- Permite generar y ejecutar la aplicación Spring Boot -->
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>

            <!-- Análisis de vulnerabilidades para Java -->
            <plugin>
                <groupId>org.owasp</groupId>
                <artifactId>dependency-check-maven</artifactId>
                <version>13.0.0</version>

                <configuration>
                    <failBuildOnCVSS>7.0</failBuildOnCVSS>

                    <nvdApiKeyEnvironmentVariable>
                        NVD_API_KEY
                    </nvdApiKeyEnvironmentVariable>

                    <nvdMaxRetryCount>20</nvdMaxRetryCount>

                    <nvdApiDelay>6000</nvdApiDelay>
                </configuration>
            </plugin>   

        </plugins>

    </build>

</project>